test

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -34,12 +34,11 @@ jobs:
           api_key: dummy
       - run: |
           echo $TEST1234
-          echo "A"
-          echo $TEST1234
-          # export LOG_FILE=java-output.log \\
-          # export TRACER_INIT_LOG="CI Visibility settings" \\
-          # java -version 2>&1 | tee $LOG_FILE \\
-          # 'grep -q "$TRACER_INIT_LOG" $LOG_FILE || { echo "Error: Output does not contain tracer initialisation log: $TRACER_INIT_LOG"; exit 1; }'
+          export LOG_FILE=java-output.log
+          echo $LOG_FILE
+          export TRACER_INIT_LOG="CI Visibility settings"
+          java -version 2>&1 | tee $LOG_FILE
+          'grep -q "$TRACER_INIT_LOG" $LOG_FILE || { echo "Error: Output does not contain tracer initialisation log: $TRACER_INIT_LOG"; exit 1; }'
 workflows:
   test-deploy:
     jobs:
