test

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -27,17 +27,20 @@ jobs:
       - image: adoptopenjdk/openjdk11:latest
     steps:
       - checkout
-      - run: export TEST1234=1234 >> $BASH_ENV
+      - run: echo 'export TEST1234=1234' >> $BASH_ENV
       # Test that the autoinstrumentation command orb works as expected.
       - test-visibility-circleci-orb/autoinstrument:
           languages: java
           service: my-service
           api_key: dummy
-      - run: |
-          export LOG_FILE=java-output.log
-          export TRACER_INIT_LOG="CI Visibility settings"
-          java -version 2>&1 | tee $LOG_FILE
-          grep -q "$TRACER_INIT_LOG" $LOG_FILE || { echo "Error: Output does not contain tracer initialisation log: $TRACER_INIT_LOG"; exit 1; }
+      - run:
+          name: test
+          command: |
+            java -version 2>&1 | tee $LOG_FILE
+            grep -q "$TRACER_INIT_LOG" $LOG_FILE || { echo "Error: Output does not contain tracer initialisation log: $TRACER_INIT_LOG"; exit 1; }
+          environment:
+            LOG_FILE: java-output.log
+            TRACER_INIT_LOG: CI Visibility settings
 workflows:
   test-deploy:
     jobs:
